# Generated by Django 3.0.6 on 2020-05-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='products/%y/%m/%d')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inside_category', to='menu.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['id'],
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(default='Ürün Kodu Giriniz', max_length=25)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('info', models.TextField(default='Ürün Aaçıklama')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('normal_price', models.CharField(db_index=True, default='SOME STRING', max_length=4)),
                ('discount', models.CharField(db_index=True, default='SOME STRING', max_length=4)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('descrip', models.CharField(db_index=True, default='Description', max_length=160)),
                ('keyword', models.CharField(db_index=True, default='Keyword', max_length=60)),
                ('page_title', models.CharField(db_index=True, default='Sayfa Title', max_length=60)),
                ('alt', models.CharField(db_index=True, default='Ürün İmage Alt Açıklaması', max_length=100)),
                ('title', models.CharField(db_index=True, default='Ürün İmage Title Açıklaması', max_length=100)),
                ('canocinal', models.CharField(db_index=True, default='https://digimaris.com/', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.Category')),
            ],
            options={
                'ordering': ('created',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
