# Generated by Django 3.0.6 on 2020-05-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_bestofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameone', models.CharField(db_index=True, max_length=15)),
                ('nametwo', models.CharField(db_index=True, max_length=15)),
                ('namethere', models.CharField(db_index=True, max_length=15)),
                ('namefour', models.CharField(db_index=True, max_length=15)),
            ],
        ),
    ]
