# Generated by Django 3.0.6 on 2020-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='nameeight',
            field=models.CharField(db_index=True, default=27, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='namefive',
            field=models.CharField(db_index=True, default=27.05, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='nameseven',
            field=models.CharField(db_index=True, default=2705, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='namesix',
            field=models.CharField(db_index=True, default=27.05, max_length=15),
            preserve_default=False,
        ),
    ]
