# Generated by Django 3.0.6 on 2020-05-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200527_2135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
