# Generated by Django 3.0.6 on 2020-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_delete_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='info',
            field=models.CharField(db_index=True, default=20.05, max_length=58),
            preserve_default=False,
        ),
    ]
