# Generated by Django 4.0.2 on 2022-06-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
