# Generated by Django 4.0.2 on 2022-06-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_no',
        ),
    ]
