# Generated by Django 4.0.2 on 2022-06-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_category_parent_remove_product_product_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BestOfWeek',
        ),
    ]
