# Generated by Django 4.0.2 on 2022-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_delete_bestofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='canocinal',
            field=models.CharField(db_index=True, default='www.centralwebagency.com', max_length=100),
        ),
    ]
