# Generated by Django 4.0.2 on 2022-06-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_cheff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cheff',
        ),
    ]
