# Generated by Django 4.0.2 on 2022-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='adress',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
    ]
