# Generated by Django 4.0.2 on 2022-06-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_restaurant_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='adress',
            new_name='link',
        ),
    ]
