# Generated by Django 4.0.2 on 2022-06-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_rename_adress_restaurant_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='day',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dayend',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='map',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twitter',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
    ]
